python: 3.8
env:
  global:
    - URL=https://raw.githubusercontent.com/horta/ci/master
    - CIBW_SKIP="cp27-* cp34-* cp35-* cp36-* *i686*"
    - CIBW_BEFORE_BUILD_LINUX="{project}/ci/linux-deps"
    - CIBW_BEFORE_BUILD_MACOS="{project}/ci/macos-deps"
    - CIBW_TEST_COMMAND="bash {project}/ci/test"
matrix:
  include:
    - os: linux
      dist: bionic
      language: python
      services: docker
      env:
        - LIBRARY_PATH=/usr/local/lib
        - NMM_EXTRA_LINK_ARGS="-Wl,-rpath,/usr/local/lib"
    # - os: osx
    #   osx_image: xcode11.2 # Python 3.7.4 running on macOS 10.14.4
    #   language: shell # 'language: python' is an error on Travis CI macOS
    #   before_install:
    #     - pip3 install --upgrade pip
    #     - pip3 install --upgrade virtualenv
    #     - virtualenv $HOME/venv # virtualenv will use Python 3
    #     - source $HOME/venv/bin/activate
addons:
  apt:
    packages:
      - libffi-dev
      - libffi6
      - cmake
install:
  - curl -fsSL https://git.io/JerYI | GITHUB_USER=horta GITHUB_PROJECT=logaddexp bash
  - curl -fsSL https://git.io/JerYI | GITHUB_USER=EBI-Metagenomics GITHUB_PROJECT=imm bash
  - curl -fsSL https://git.io/JerYI | GITHUB_USER=EBI-Metagenomics GITHUB_PROJECT=nmm bash
  - curl -fsSL $URL/check-readme.sh | bash
  - curl -fsSL $URL/py-min-deps.sh | bash -s -- --numpy --scipy
  - curl -fsSL $URL/py-check-style.sh | bash
  - curl -fsSL $URL/py-dev-test.sh | bash
  - curl -fsSL $URL/py-sdist-test.sh | bash
  - python3 -m pip install cibuildwheel
script:
  - python3 -m cibuildwheel --output-dir wheelhouse
after_success:
  - |
    if [ "${TRAVIS_TAG:-}" != "" ]; then
      python3 -m pip install twine -U
      python3 -m twine upload --skip-existing wheelhouse/*
    fi
  - git clean -xdfq
notifications:
  email:
    recipients:
      - danilo.horta@pm.me
    on_success: never
    on_failure: always
