[build-system]
requires = ["setuptools >= 47.1.1", "wheel >= 0.34.2", "imm >= 0.0.2"]
build-backend = "setuptools.build_meta"

[tool.isort]
profile = "black"
src_paths = ["nmm"]
known_third_party = ["cffi", "imm", "pytest"]
